### ISSUE TITLE
Python 3.4 issue..simple fix

### ISSUE THREAD

**Issue by sirvon** [mixpanel/mixpanel-python#55]
```java
Traceback (most recent call last):
  File "ClientTokenQ.py", line 4, in <module>
    from lib import queueMixin as qm
  File "/home/creator/apps/xnainfra/lib/queueMixin.py", line 12, in <module>
    from mixpanel import Mixpanel
  File "/usr/local/lib/python3.4/site-packages/mixpanel/__init__.py", line 209
    except Exception, e:
```

```java
except Exception as e:
```

**Comment by zakj** [comment]
Thanks for the report! I'm curious how you installed the mixpanel library, and what version you're using. The latest version of this library passes tests on Python 3.4, and [line 209](https://github.com/mixpanel/mixpanel-python/blob/master/mixpanel/__init__.py#L209) doesn't match your traceback.

**Comment by sirvon** [comment]
```bash
creator@creator:~/apps/xnainfra$ pip3 --version
pip 6.0.8 from /usr/local/lib/python3.4/site-packages (python 3.4)
creator@creator:~/apps/xnainfra$ python3 --version
Python 3.4.3
creator@creator:~/apps/xnainfra$ sudo pip3 install mixpanel-python
[sudo] password for creator: 
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): mixpanel-python in /usr/local/lib/python3.4/site-packages
Successfully installed pip-7.1.2
creator@creator:~/apps/xnainfra$ sudo pip3 install mixpanel-python
Requirement already satisfied (use --upgrade to upgrade): mixpanel-python in /usr/local/lib/python3.4/site-packages

```

**Comment by zakj** [comment]
Thanks! A couple more commands that might help:

```
grep -i version /usr/local/lib/python3.4/site-packages/mixpanel/__init__.py
pip install --upgrade mixpanel-python
```

**Comment by sirvon** [comment]
```bash
creator@creator:~/apps/xnainfra$ grep -i version /usr/local/lib/python3.4/site-packages/mixpanel/__init__.py
Requires `curl`, the simplejson or json lib, and Python version 2.4 or higher.  mixpanel-python is intended
        This function requires `curl` and Python version 2.4 or higher.
creator@creator:~/apps/xnainfra$ sudo pip3 install --upgrade mixpanel-python
Requirement already up-to-date: mixpanel-python in /usr/local/lib/python3.4/site-packages
creator@creator:~/apps/xnainfra$
```

**Comment by zakj** [comment]
Aha! There's the trouble. The official Mixpanel client (this one) is known on PyPi as simply "mixpanel": https://pypi.python.org/pypi/mixpanel

You have the https://pypi.python.org/pypi/mixpanel-python package installed, which we do not support. If you're not depending specifically on the features offered by that package, you should be able to:

```
sudo pip3 uninstall mixpanel-python
sudo pip3 install mixpanel
```

**Comment by sirvon** [comment]
thanks man! niceeeee!

**Comment by zakj** [comment]
Awesome, glad that worked!
