### ISSUE TITLE
trying to fire an event in mixpanel but getting below error

### ISSUE THREAD

**Issue by mhassaanmughal** [mixpanel/mixpanel-python#78]
Traceback (most recent call last):
  File "mixpanelEvent.py", line 194, in <module>
    mp.track(123, 'ABC')
  File "/usr/local/lib/python2.7/dist-packages/mixpanel/__init__.py", line 95, in track
    self._consumer.send('events', json_dumps(event, cls=self._serializer))
  File "/usr/local/lib/python2.7/dist-packages/mixpanel/__init__.py", line 488, in send
    self._write_request(self._endpoints[endpoint], json_message, api_key)
  File "/usr/local/lib/python2.7/dist-packages/mixpanel/__init__.py", line 511, in _write_request
    six.raise_from(MixpanelException(e), e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 740, in raise_from
    raise value
mixpanel.MixpanelException: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

using python 2.7

**Comment by seizethedave** [comment]
Hi, are you still having this problem? It looks like some kind local config issue. I found some others having the same problem and they pointed at this as a fix that often works: https://github.com/tensorflow/tensorflow/issues/10779#issuecomment-313514199
